---
- name: Install sysstat with config files on Amazon Linux 2
  hosts: all
  become: yes

  tasks:
    - name: Update the package cache
      yum: name=sysstat state=latest

    - name: Copy custom sysstat configuration files
      copy:
        src: sysstat.conf
        dest: /etc/sysstat/sysstat.conf
        mode: 0644
      loop: [1, 2]

    - name: Start sysstat services
      service: name=sysstat state=started
      with_items: [1, 2]
      loop_control:
        loop_var: instance
      tags:
        - sysstat

  handlers:
    - name: restart sysstat services
      service: name=sysstat state=restarted
      tags:
        - sysstat
